### PR TITLE
New arsenal framework

### PR DESCRIPTION
**Pull request by Whitsel**
This paves the way for the full arsenal framework. Much easier to manage and make changes to as needed.

The entire framework is up. The classes themselves need to get unfucked first though, namely infantry sharing classes with the sabre and MPs, infidel shasring classes with atlas 4 and zeuses.
They just need to be given their own classes, and then each class has to have one of these lines added to their class init (https://github.com/7Cav/7Cav-Insurgency/tree/develop/7Cav-Insurgency.lythium/scripts/class) depending on what they are
```
    call scripts_fnc_arsenalAdmin; //Adds all arsenals
    call scripts_fnc_arsenalInfantry;
    call scripts_fnc_arsenalMedic;
    call scripts_fnc_arsenalLogistics;
    call scripts_fnc_arsenalLongshot;
    call scripts_fnc_arsenalTanker;
    call scripts_fnc_arsenalHeliPilot;
    call scripts_fnc_arsenalHeliCrew;
    call scripts_fnc_arsenalPlanePilot;
```

Once that's done the old arsenal_loadouts.sqf can be deleted and it's block in the initPlayerLocal.sqf can be removed
```
{[_x] execVM "scripts\arsenal_loadouts.sqf";} forEach [
    arsenal_1,
    arsenal_2,
    arsenal_3,
    arsenal_4,
    arsenal_5,
    arsenal_6,
    arsenal_7,
    arsenal_8
]
```

### CODE REVIEW

**Comment by Whitsel** [comment]
This download has the demo mission file with everything set up
https://cdn.discordapp.com/attachments/795589823842746378/806417859332145192/Tac2_Arsenal_Demo.VR.rar

**Comment by Whitsel** [comment]
This does contain a check to not iterate on arsenals that do not exist but for now I still have just the arsenal present on the map listed.

**Comment by Whitsel** [comment]
Things to check

- [ ] MPs and Zeus still have perms
- [ ] Atlas 4 still has fortify perms

**Comment by Whitsel** [comment]
https://github.com/7Cav/7Cav-Insurgency/pull/45

**Review by 7cavZlobinN — APPROVED** [review]

**Pull request merged**
